name: Deploy to Heroku

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Heroku
    steps:
      - uses: actions/checkout@v2
      - name: Dpl to heroku
        uses: tiagogouvea/github-dpl-action@master
        with:
          provider: "heroku"
          app: ${{secrets.HEROKU_APP_NAME}}
          api-key: ${{secrets.HEROKU_API}}
